import os
import sys
import pytest

sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))



from tests.new_fixtures import (
    holder, is_subset
)
from sqlleaf.objects.query_types import InsertQuery, UpdateQuery, SequenceQuery

DIALECT = 'postgres'


def test__table_like_table(holder):
    queries = '''
    CREATE TABLE fruit.a (
        name VARCHAR,
        age INT DEFAULT 42,
        gen TEXT GENERATED ALWAYS AS ( name || 'x') STORED,
        id INT GENERATED BY DEFAULT AS IDENTITY
    );
    CREATE TABLE fruit.c_like_a (label VARCHAR, LIKE fruit.a EXCLUDING ALL INCLUDING DEFAULTS, color VARCHAR);
    CREATE TABLE fruit.b_like_a (LIKE fruit.a EXCLUDING ALL INCLUDING DEFAULTS, label VARCHAR, color VARCHAR);

    INSERT INTO fruit.b_like_a (name, age, id) SELECT name, age, id FROM fruit.a;
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_friendly_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()
    queries = h.get_queries_created()

    assert len(nodes) == 7
    assert len(edges) == 4
    assert paths == [
        ['column[fruit.a.name]', 'column[fruit.b_like_a.name]'],
        ['literal[42]', 'column[fruit.b_like_a.age]'],
        ['column[fruit.a.age]', 'column[fruit.b_like_a.age]'],
        ['column[fruit.a.id]', 'column[fruit.b_like_a.id]']
    ]
    # Test the LIKE declaration position
    cols = queries[1].column_defs
    assert (cols[0].name, cols[-1].name) == ('label', 'color')
    cols = queries[2].column_defs
    assert (cols[0].name, cols[-1].name) == ('name', 'color')


# TODO: LIKE with column default overrides


def test__table_like_table_generated(holder):
    queries = '''
    CREATE TABLE fruit.a (
        name VARCHAR,
        kind TEXT,
        gen TEXT GENERATED ALWAYS AS ( concat(name, kind) ) STORED
    );
    CREATE TABLE fruit.b_like_a (LIKE fruit.a INCLUDING GENERATED);

    INSERT INTO fruit.b_like_a (name, kind) SELECT 'banana' as name, 'fruit' as kind;
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_full_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert len(edges) == 5
    assert paths == [
        ['literal["banana"]', 'column[fruit.b_like_a.name]', 'function[CONCAT()]', 'column[fruit.b_like_a.gen]'],
        ['literal["fruit"]', 'column[fruit.b_like_a.kind]', 'function[CONCAT()]', 'column[fruit.b_like_a.gen]']
    ]
    assert is_subset(subarr=[
        'column[fruit.b_like_a.gen type=TEXT subkind=table]',
        'column[fruit.b_like_a.kind type=TEXT subkind=table]',
        'column[fruit.b_like_a.name type=VARCHAR subkind=table]'
    ], arr=nodes)


def test__table_with_default_columns(holder):
    queries = '''
    CREATE TABLE fruit (name varchar, size int default 1, age int default 42);

    INSERT INTO fruit
    SELECT 'apple' as name, 10 as size;
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_friendly_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert paths == [
        ['literal["apple"]', 'column[fruit.name]'],
        ['literal[1]', 'column[fruit.size]'],
        ['literal[10]', 'column[fruit.size]'],
        ['literal[42]', 'column[fruit.age]']
    ]


# TODO: LIKE + INHERITS with same columns


def test__table_inherits_with_select(holder):
    queries = '''
    CREATE TABLE fruit.b (type VARCHAR, kind VARCHAR);
    CREATE TABLE fruit.b_only (type VARCHAR);
    CREATE TABLE fruit.x (label VARCHAR) INHERITS (fruit.b);
    CREATE TABLE fruit.y (label VARCHAR) INHERITS (fruit.b);
    CREATE TABLE fruit.x_y (value VARCHAR);
    CREATE TABLE fruit.all (name VARCHAR);

    INSERT INTO fruit.b (type) SELECT 'apple' AS type;
    -- Ensure only parent is selected
    INSERT INTO fruit.b_only (type) SELECT type FROM ONLY fruit.b;

    -- Ensure parent includes children
    INSERT INTO fruit.all (name) SELECT kind from fruit.b;

    -- Ensure children include only themselves
    INSERT INTO fruit.x_y (value) SELECT label FROM fruit.x;
    INSERT INTO fruit.x_y (value) SELECT label FROM fruit.y;
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_full_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert len(nodes) == 10
    assert paths == [
        ['literal["apple"]', 'column[fruit.b.type]', 'column[fruit.b_only.type]'],
        ['column[fruit.b.kind]', 'column[fruit.all.name]'],
        ['column[fruit.x.kind]', 'column[fruit.all.name]'],
        ['column[fruit.y.kind]', 'column[fruit.all.name]'],
        ['column[fruit.x.label]', 'column[fruit.x_y.value]'],
        ['column[fruit.y.label]', 'column[fruit.x_y.value]']
    ]


def test__table_inherits_with_merge(holder):
    queries = '''
    CREATE TABLE a (type VARCHAR, kind VARCHAR);
    CREATE TABLE b (type VARCHAR, kind VARCHAR, color VARCHAR);
    CREATE TABLE c (color VARCHAR);
    CREATE TABLE fruit.x (label VARCHAR) INHERITS (b);
    CREATE TABLE fruit.y (label VARCHAR) INHERITS (b);

    -- Ensure parent includes children
    MERGE INTO b AS t
    USING a AS s
    ON t.type = s.type
    WHEN MATCHED THEN
        UPDATE SET type = s.type
    WHEN NOT MATCHED THEN
        INSERT (type) VALUES (s.type);

    -- Ensure only parent is selected as target
    MERGE INTO ONLY b AS t
    USING a AS s
    ON t.kind = s.kind
    WHEN MATCHED THEN
        UPDATE SET kind = s.kind
    WHEN NOT MATCHED THEN
        INSERT (kind) VALUES (s.kind);

    -- Ensure only parent is selected as source
    MERGE INTO c AS t
    USING ONLY b AS s
    ON t.color = s.color
    WHEN MATCHED THEN
        UPDATE SET color = s.color
    WHEN NOT MATCHED THEN
        INSERT (color) VALUES (s.color);
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_full_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert len(nodes) == 8
    assert paths == [
        ['column[a.type]', 'column[b.type]'],
        ['column[a.type]', 'column[fruit.x.type]'],
        ['column[a.type]', 'column[fruit.y.type]'],
        ['column[a.kind]', 'column[b.kind]'],
        ['column[b.color]', 'column[c.color]']
    ]


# TODO: UPDATE and SELECT from different inherited tables in the same query
# TODO: test ONLY inside a CTE to verify new table lookup logic


view_types = ['', 'MATERIALIZED']
@pytest.mark.parametrize("case", view_types)
def test__view_simple(holder, case):
    queries = f'''CREATE {case} VIEW one AS SELECT -1 as number;'''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    paths = h.get_friendly_paths()

    assert paths == [['literal[-1]', 'column[one.number]']]


def test__views_and_ctas_with_every_hierarchy(holder):
    queries = '''
    CREATE TABLE b.a (ba int);
    CREATE TABLE a.b (ab int);
    CREATE TABLE ctas AS SELECT ab as one FROM a.b;
    CREATE VIEW vie.tab AS SELECT * FROM ctas;
    CREATE VIEW tab.vie AS SELECT ABS(one) AS two FROM vie.tab;
    CREATE VIEW sch.tab.vie AS SELECT two AS three FROM tab.vie
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_full_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert len(nodes) == 6
    assert len(edges) == 5
    assert paths == [
        ['column[a.b.ab]', 'column[ctas.one]', 'column[vie.tab.one]', 'function[ABS()]', 'column[tab.vie.two]', 'column[sch.tab.vie.three]']
    ]


def test__view_with_cte(holder):
    queries = '''
    CREATE VIEW v AS
    WITH inner1 AS (
        SELECT 'a' as name
    )
    SELECT * FROM inner1;
    '''
    h = holder()
    h.generate(queries, dialect='postgres')
    paths = h.get_friendly_paths()

    assert paths == [
        ['literal["a"]', 'column[inner1.name]', 'column[v.name]']
    ]


def test__simple_sequence(holder):
    queries = '''
    CREATE SEQUENCE serial START 101;
    INSERT INTO fruit.raw (age) SELECT nextval('serial') as age;
    '''
    h = holder(with_tables=True)
    h.generate(queries, dialect=DIALECT)
    queries = h.get_queries_created()
    paths = h.get_friendly_paths()

    assert paths == [['sequence[serial]', 'column[fruit.raw.age]']]
    assert [SequenceQuery, InsertQuery] == list(map(type, queries))
