import os
import sys
import pytest

sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))



from tests.new_fixtures import (
    holder, is_subset
)
from sqlleaf.objects.query_types import InsertQuery, UpdateQuery, SequenceQuery

DIALECT = 'postgres'

def test__table_like_table(holder):
    queries = '''
    CREATE TABLE fruit.a (
        name varchar,
        age int default 42,
        gen TEXT GENERATED ALWAYS AS ( name || 'x') STORED,
        id INT GENERATED BY DEFAULT AS IDENTITY
    );
    CREATE TABLE fruit.b_like_a (LIKE fruit.a EXCLUDING ALL INCLUDING DEFAULTS, label varchar);

    INSERT INTO fruit.b_like_a (name, age, id) SELECT name, age, id FROM fruit.a;
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_friendly_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert len(nodes) == 7
    assert len(edges) == 4
    assert paths == [
        ['column[fruit.a.name]', 'column[fruit.b_like_a.name]'],
        ['literal[42]', 'column[fruit.b_like_a.age]'],
        ['column[fruit.a.age]', 'column[fruit.b_like_a.age]'],
        ['column[fruit.a.id]', 'column[fruit.b_like_a.id]']
    ]


def test__table_like_table_generated(holder):
    queries = '''
    CREATE TABLE fruit.a (
        name VARCHAR,
        kind TEXT,
        gen TEXT GENERATED ALWAYS AS ( concat(name, kind) ) STORED
    );
    CREATE TABLE fruit.b_like_a (LIKE fruit.a INCLUDING GENERATED);

    INSERT INTO fruit.b_like_a (name, kind) SELECT 'banana' as name, 'fruit' as kind;
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_full_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert len(edges) == 5
    assert paths == [
        ['literal["banana"]', 'column[fruit.b_like_a.name]', 'function[CONCAT()]', 'column[fruit.b_like_a.gen]'],
        ['literal["fruit"]', 'column[fruit.b_like_a.kind]', 'function[CONCAT()]', 'column[fruit.b_like_a.gen]']
    ]
    assert is_subset(subarr=[
        'column[fruit.b_like_a.gen type=TEXT subkind=table]',
        'column[fruit.b_like_a.kind type=TEXT subkind=table]',
        'column[fruit.b_like_a.name type=VARCHAR subkind=table]'
    ], arr=nodes)


def test__table_with_default_columns(holder):
    queries = '''
    CREATE TABLE fruit (name varchar, size int default 1, age int default 42);

    INSERT INTO fruit
    SELECT 'apple' as name, 10 as size;
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_friendly_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert paths == [
        ['literal["apple"]', 'column[fruit.name]'],
        ['literal[1]', 'column[fruit.size]'],
        ['literal[10]', 'column[fruit.size]'],
        ['literal[42]', 'column[fruit.age]']
    ]


@pytest.mark.skip(reason="todo")
def test__table_inherits_table(holder):
    queries = '''
    CREATE TABLE fruit.a (name varchar, age int default 42);
    CREATE TABLE fruit.b_inherits_a (label varchar) INHERITS (fruit.a);
    CREATE TABLE fruit.c (name varchar);

    INSERT INTO fruit.c SELECT name FROM fruit.a;
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)

    # expect: fruit.a.name -> fruit.processed.name
    # expect: fruit.b_inherits_a.name -> fruit.processed.name

view_types = ['', 'MATERIALIZED']
@pytest.mark.parametrize("case", view_types)
def test__view_simple(holder, case):
    queries = f'''CREATE {case} VIEW one AS SELECT -1 as number;'''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    paths = h.get_friendly_paths()

    assert paths == [['literal[-1]', 'column[one.number]']]


def test__views_and_ctas_with_every_hierarchy(holder):
    queries = '''
    CREATE TABLE b.a (ba int);
    CREATE TABLE a.b (ab int);
    CREATE TABLE ctas AS SELECT ab as one FROM a.b;
    CREATE VIEW vie.tab AS SELECT * FROM ctas;
    CREATE VIEW tab.vie AS SELECT ABS(one) AS two FROM vie.tab;
    CREATE VIEW sch.tab.vie AS SELECT two AS three FROM tab.vie
    '''
    h = holder()
    h.generate(queries, dialect=DIALECT)
    nodes = h.get_full_node_names()
    edges = h.get_edges()
    paths = h.get_friendly_paths()

    assert len(nodes) == 6
    assert len(edges) == 5
    assert paths == [
        ['column[a.b.ab]', 'column[ctas.one]', 'column[vie.tab.one]', 'function[ABS()]', 'column[tab.vie.two]', 'column[sch.tab.vie.three]']
    ]


def test__view_with_cte(holder):
    queries = '''
    CREATE VIEW v AS
    WITH inner1 AS (
        SELECT 'a' as name
    )
    SELECT * FROM inner1;
    '''
    h = holder()
    h.generate(queries, dialect='postgres')
    paths = h.get_friendly_paths()

    assert paths == [
        ['literal["a"]', 'column[inner1.name]', 'column[v.name]']
    ]


def test__simple_sequence(holder):
    queries = '''
    CREATE SEQUENCE serial START 101;
    INSERT INTO fruit.raw (age) SELECT nextval('serial') as age;
    '''
    h = holder(with_tables=True)
    h.generate(queries, dialect=DIALECT)
    queries = h.get_queries_created()
    paths = h.get_friendly_paths()

    assert paths == [['sequence[serial]', 'column[fruit.raw.age]']]
    assert [SequenceQuery, InsertQuery] == list(map(type, queries))
