import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))


from tests.new_fixtures import holder, is_subset
from sqlleaf.objects.query_types import InsertQuery, SequenceQuery

DIALECT = "postgres"


def test__table_types(holder):
    sql = """
    CREATE TEMPORARY TABLE fruit.new (age INT);

    INSERT INTO fruit.new (age) VALUES (1);
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert "column[fruit.new.age type=INT kind=table subkind=temporary]" in h.nodes_full


def test__table_like_table(holder):
    sql = """
    CREATE TABLE fruit.a (
        name VARCHAR,
        age INT DEFAULT 42,
        gen TEXT GENERATED ALWAYS AS ( name || 'x') STORED,
        id INT GENERATED BY DEFAULT AS IDENTITY
    );
    CREATE TABLE fruit.c_like_a (label VARCHAR, LIKE fruit.a EXCLUDING ALL INCLUDING DEFAULTS, color VARCHAR);
    CREATE TABLE fruit.b_like_a (LIKE fruit.a EXCLUDING ALL INCLUDING DEFAULTS, label VARCHAR, color VARCHAR);

    INSERT INTO fruit.b_like_a (name, age, id) SELECT name, age, id FROM fruit.a;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ["column[fruit.a.name]", "column[fruit.b_like_a.name]"],
        ["literal[42]", "column[fruit.b_like_a.age]"],
        ["column[fruit.a.age]", "column[fruit.b_like_a.age]"],
        ["column[fruit.a.id]", "column[fruit.b_like_a.id]"],
    ]
    # Test the LIKE declaration position
    cols = h.queries[1].column_defs
    assert (cols[0].name, cols[-1].name) == ("label", "color")
    cols = h.queries[2].column_defs
    assert (cols[0].name, cols[-1].name) == ("name", "color")
    assert len(h.nodes) == 7
    assert len(h.edges) == 4


# TODO: LIKE with column default overrides


def test__table_like_table_generated(holder):
    sql = """
    CREATE TABLE fruit.a (
        name VARCHAR,
        kind TEXT,
        gen TEXT GENERATED ALWAYS AS ( concat(name, kind) ) STORED
    );
    CREATE TABLE fruit.b_like_a (LIKE fruit.a INCLUDING GENERATED);

    INSERT INTO fruit.b_like_a (name, kind) SELECT 'banana' as name, 'fruit' as kind;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ['literal["banana"]', "column[fruit.b_like_a.name]", "function[CONCAT()]", "column[fruit.b_like_a.gen]"],
        ['literal["fruit"]', "column[fruit.b_like_a.kind]", "function[CONCAT()]", "column[fruit.b_like_a.gen]"],
    ]
    assert is_subset(
        subarr=[
            "column[fruit.b_like_a.gen type=TEXT kind=table]",
            "column[fruit.b_like_a.kind type=TEXT kind=table]",
            "column[fruit.b_like_a.name type=VARCHAR kind=table]",
        ],
        arr=h.nodes_full,
    )
    assert len(h.nodes) == 6
    assert len(h.edges) == 5


def test__table_with_default_columns(holder):
    sql = """
    CREATE TABLE fruit (name varchar, size int default 1, age int default 42);

    INSERT INTO fruit
    SELECT 'apple' as name, 10 as size;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ['literal["apple"]', "column[fruit.name]"],
        ["literal[1]", "column[fruit.size]"],
        ["literal[10]", "column[fruit.size]"],
        ["literal[42]", "column[fruit.age]"],
    ]
    assert len(h.nodes) == 7
    assert len(h.edges) == 4


# TODO: LIKE + INHERITS with same columns


def test__table_inherits_with_select(holder):
    sql = """
    CREATE TABLE fruit.a (type VARCHAR, kind VARCHAR);
    CREATE TABLE fruit.a_only () INHERITS (fruit.a);
    CREATE TABLE fruit.output (type VARCHAR, kind VARCHAR);

    CREATE TABLE fruit.b (type VARCHAR, kind VARCHAR);
    CREATE TABLE fruit.b_only (type VARCHAR);
    CREATE TABLE fruit.x (label VARCHAR) INHERITS (fruit.b);
    CREATE TABLE fruit.y (label VARCHAR) INHERITS (fruit.b);
    CREATE TABLE fruit.x_y (value VARCHAR);
    CREATE TABLE fruit.all (name VARCHAR);

    INSERT INTO fruit.b (type) SELECT 'apple' AS type;
    -- Ensure only parent is selected
    INSERT INTO fruit.b_only (type) SELECT type FROM ONLY fruit.b;

    -- Ensure only parent is selected
    INSERT INTO fruit.output TABLE ONLY fruit.a;

    -- Ensure parent includes children
    INSERT INTO fruit.all (name) SELECT kind from fruit.b;

    -- Ensure children include only themselves
    INSERT INTO fruit.x_y (value) SELECT label FROM fruit.x;
    INSERT INTO fruit.x_y (value) SELECT label FROM fruit.y;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ['literal["apple"]', "column[fruit.b.type]", "column[fruit.b_only.type]"],
        ["column[fruit.a.type]", "column[fruit.output.type]"],
        ["column[fruit.a.kind]", "column[fruit.output.kind]"],
        ["column[fruit.b.kind]", "column[fruit.all.name]"],
        ["column[fruit.x.kind]", "column[fruit.all.name]"],
        ["column[fruit.y.kind]", "column[fruit.all.name]"],
        ["column[fruit.x.label]", "column[fruit.x_y.value]"],
        ["column[fruit.y.label]", "column[fruit.x_y.value]"],
    ]
    assert len(h.nodes) == 14
    assert len(h.edges) == 9


def test__table_inherits_with_merge(holder):
    sql = """
    CREATE TABLE a (type VARCHAR, kind VARCHAR);
    CREATE TABLE b (type VARCHAR, kind VARCHAR, color VARCHAR);
    CREATE TABLE c (color VARCHAR);
    CREATE TABLE fruit.x (label VARCHAR) INHERITS (b);
    CREATE TABLE fruit.y (label VARCHAR) INHERITS (b);

    -- Ensure parent includes children
    MERGE INTO b AS t
    USING a AS s
    ON t.type = s.type
    WHEN MATCHED THEN
        UPDATE SET type = s.type
    WHEN NOT MATCHED THEN
        INSERT (type) VALUES (s.type);

    -- Ensure only parent is selected as target
    MERGE INTO ONLY b AS t
    USING a AS s
    ON t.kind = s.kind
    WHEN MATCHED THEN
        UPDATE SET kind = s.kind
    WHEN NOT MATCHED THEN
        INSERT (kind) VALUES (s.kind);

    -- Ensure only parent is selected as source
    MERGE INTO c AS t
    USING ONLY b AS s
    ON t.color = s.color
    WHEN MATCHED THEN
        UPDATE SET color = s.color
    WHEN NOT MATCHED THEN
        INSERT (color) VALUES (s.color);
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ['column[a.type]', 'column[b.type]'],
        ['column[a.type]', 'column[b.type]'],
        ['column[a.type]', 'column[fruit.x.type]'],
        ['column[a.type]', 'column[fruit.y.type]'],
        ['column[a.kind]', 'column[b.kind]'],
        ['column[a.kind]', 'column[b.kind]'],
        ['column[b.color]', 'column[c.color]'],
        ['column[b.color]', 'column[c.color]']
    ]
    assert len(h.nodes) == 8
    assert len(h.edges) == 8


# Not supported by sqlglot: 'Falling back to Command'
def test__table_foreign(holder):
    sql = """
    CREATE FOREIGN TABLE foreign_users (
        id integer NOT NULL,
        username text,
        email text
    )
    SERVER remote_server_name
    OPTIONS (schema_name 'public', table_name 'users');
    """
    h = holder(sql=sql, dialect=DIALECT)
    assert len(h.queries) == 0


# Not supported by sqlglot (both): 'Falling back to Command'
def test__table_of_type(holder):
    sql = """
    CREATE TYPE person_type AS (
        first_name text,
        last_name text,
        age integer
    );

    CREATE TABLE employees OF person_type (
        PRIMARY KEY (first_name, last_name)
    );
    """
    h = holder(sql=sql, dialect=DIALECT)
    assert len(h.queries) == 0


# TODO: UPDATE and SELECT from different inherited tables in the same query
# TODO: test ONLY inside a CTE to verify new table lookup logic


def test__simple_sequence(holder):
    sql = """
    CREATE SEQUENCE serial START 101;
    INSERT INTO fruit.raw (age) SELECT nextval('serial') as age;
    """
    h = holder(sql=sql, dialect=DIALECT, with_tables=True)

    assert h.paths == [["sequence[serial]", "column[fruit.raw.age]"]]
    assert [SequenceQuery, InsertQuery] == list(map(type, h.queries))
    assert len(h.nodes) == 2
    assert len(h.edges) == 1
