import os
import sys

import pytest
import sqlglot

from sqlleaf.exception import SqlLeafException
from tests.new_fixtures import holder as holder

sys.path.append(os.path.join(os.path.dirname(__file__), "..", "..", ".."))

from sqlleaf.models.query import TableQuery, TypeQuery

DIALECT = "postgres"


def test__table_types(holder):
    sql = """
    CREATE TEMPORARY TABLE fruit.new (age INT);

    INSERT INTO fruit.new (age) VALUES (1);
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [["literal[1]", "column[fruit.new.age]"]]
    assert h.nodes_full == [
        "literal[name=1 type=INT position=[query_depth=0 query_width=0 statement=1 select=0 func_depth=0 func_arg=0]]",
        "column[name=age type=INT properties=[kind=table subkind=temporary table=new schema=fruit]]",
    ]
    assert len(h.nodes) == 2
    assert len(h.edges) == 1


def test__table_empty(holder):
    sql = """
    CREATE TABLE fruit.new ();
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == []
    assert h.nodes_full == []
    assert len(h.nodes) == 0
    assert len(h.edges) == 0
    assert isinstance(h.queries_original[0], TableQuery)


def test__table_like_table(holder):
    sql = """
    CREATE TABLE fruit.a (
        name VARCHAR,
        age INT DEFAULT 42,
        gen TEXT GENERATED ALWAYS AS ( name || 'x') STORED,
        id INT GENERATED BY DEFAULT AS IDENTITY
    );
    CREATE TABLE fruit.c_like_a (label VARCHAR, LIKE fruit.a EXCLUDING ALL INCLUDING DEFAULTS, color VARCHAR);
    CREATE TABLE fruit.b_like_a (LIKE fruit.a EXCLUDING ALL INCLUDING DEFAULTS, label VARCHAR, color VARCHAR);

    INSERT INTO fruit.b_like_a (name, age, id) SELECT name, age, id FROM fruit.a;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ["column[fruit.a.name]", "column[fruit.b_like_a.name]"],
        ["literal[42]", "column[fruit.b_like_a.age]"],
        ["column[fruit.a.age]", "column[fruit.b_like_a.age]"],
        ["column[fruit.a.id]", "column[fruit.b_like_a.id]"],
    ]
    # Test the LIKE declaration position
    cols = h.queries_original[1].column_defs
    assert (cols[0].name, cols[-1].name) == ("label", "color")
    cols = h.queries_original[2].column_defs
    assert (cols[0].name, cols[-1].name) == ("name", "color")
    assert len(h.nodes) == 7
    assert len(h.edges) == 4


# TODO: LIKE with column default overrides


def test__table_like_table_generated(holder):
    sql = """
    CREATE TABLE fruit.a (
        name VARCHAR,
        kind TEXT,
        gen TEXT GENERATED ALWAYS AS ( concat(name, kind) ) STORED
    );
    CREATE TABLE fruit.b_like_a (LIKE fruit.a INCLUDING GENERATED);

    INSERT INTO fruit.b_like_a (name, kind) SELECT 'banana' as name, 'fruit' as kind;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ['literal["banana"]', "column[fruit.b_like_a.name]", "function[CONCAT]", "column[fruit.b_like_a.gen]"],
        ['literal["fruit"]', "column[fruit.b_like_a.kind]", "function[CONCAT]", "column[fruit.b_like_a.gen]"],
    ]
    assert "column[name=gen type=TEXT properties=[kind=table table=b_like_a schema=fruit]]" in h.nodes_full
    assert "column[name=kind type=TEXT properties=[kind=table table=b_like_a schema=fruit]]" in h.nodes_full
    assert "column[name=name type=VARCHAR properties=[kind=table table=b_like_a schema=fruit]]" in h.nodes_full
    assert len(h.nodes) == 6
    assert len(h.edges) == 5


# TODO: LIKE + INHERITS with same columns


def test__table_inherits_with_select(holder):
    sql = """
    CREATE TABLE fruit.a (type VARCHAR, kind VARCHAR);
    CREATE TABLE fruit.a_only () INHERITS (fruit.a);
    CREATE TABLE fruit.output (type VARCHAR, kind VARCHAR);

    CREATE TABLE fruit.b (type VARCHAR, kind VARCHAR);
    CREATE TABLE fruit.b_only (type VARCHAR);
    CREATE TABLE fruit.x (label VARCHAR) INHERITS (fruit.b);
    CREATE TABLE fruit.y (label VARCHAR) INHERITS (fruit.b);
    CREATE TABLE fruit.x_y (value VARCHAR);
    CREATE TABLE fruit.all (name VARCHAR);

    INSERT INTO fruit.b (type) SELECT 'apple' AS type;
    -- Ensure only parent is selected
    INSERT INTO fruit.b_only (type) SELECT type FROM ONLY fruit.b;

    -- Ensure only parent is selected
    INSERT INTO fruit.output TABLE ONLY fruit.a;

    -- Ensure parent includes children
    INSERT INTO fruit.all (name) SELECT kind from fruit.b;

    -- Ensure children include only themselves
    INSERT INTO fruit.x_y (value) SELECT label FROM fruit.x;
    INSERT INTO fruit.x_y (value) SELECT label FROM fruit.y;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ['literal["apple"]', "column[fruit.b.type]", "column[fruit.b_only.type]"],
        ["column[fruit.a.type]", "column[fruit.output.type]"],
        ["column[fruit.a.kind]", "column[fruit.output.kind]"],
        ["column[fruit.b.kind]", "column[fruit.all.name]"],
        ["column[fruit.x.kind]", "column[fruit.all.name]"],
        ["column[fruit.y.kind]", "column[fruit.all.name]"],
        ["column[fruit.x.label]", "column[fruit.x_y.value]"],
        ["column[fruit.y.label]", "column[fruit.x_y.value]"],
    ]
    assert len(h.nodes) == 14
    assert len(h.edges) == 9


def test__table_inherits_with_merge(holder):
    sql = """
    CREATE TABLE a (type VARCHAR, kind VARCHAR);
    CREATE TABLE b (type VARCHAR, kind VARCHAR, color VARCHAR);
    CREATE TABLE c (color VARCHAR);
    CREATE TABLE fruit.x (label VARCHAR) INHERITS (b);
    CREATE TABLE fruit.y (label VARCHAR) INHERITS (b);

    -- Ensure parent includes children
    MERGE INTO b AS t
    USING a AS s
    ON t.type = s.type
    WHEN MATCHED THEN
        UPDATE SET type = s.type
    WHEN NOT MATCHED THEN
        INSERT (type) VALUES (s.type);

    -- Ensure only parent is selected as target
    MERGE INTO ONLY b AS t
    USING a AS s
    ON t.kind = s.kind
    WHEN MATCHED THEN
        UPDATE SET kind = s.kind
    WHEN NOT MATCHED THEN
        INSERT (kind) VALUES (s.kind);

    -- Ensure only parent is selected as source
    MERGE INTO c AS t
    USING ONLY b AS s
    ON t.color = s.color
    WHEN MATCHED THEN
        UPDATE SET color = s.color
    WHEN NOT MATCHED THEN
        INSERT (color) VALUES (s.color);
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [
        ["column[a.type]", "column[b.type]"],
        ["column[a.type]", "column[b.type]"],
        ["column[a.type]", "column[fruit.x.type]"],
        ["column[a.type]", "column[fruit.y.type]"],
        ["column[a.kind]", "column[b.kind]"],
        ["column[a.kind]", "column[b.kind]"],
        ["column[b.color]", "column[c.color]"],
        ["column[b.color]", "column[c.color]"],
    ]
    assert len(h.nodes) == 8
    assert len(h.edges) == 8


def test__table_fails_missing_column_type(holder):
    with pytest.raises(SqlLeafException) as e:
        sql = """
        CREATE TABLE fail (a INT, b);
        """
        holder(sql=sql, dialect=DIALECT)

    assert e.value.args[0] == "Column 'b' must define a data type."


# Not supported by sqlglot: 'Falling back to Command'
def test__table_foreign(holder):
    sql = """
    CREATE FOREIGN TABLE foreign_users (
        id integer NOT NULL,
        username text,
        email text
    )
    SERVER remote_server_name
    OPTIONS (schema_name 'public', table_name 'users');
    """
    h = holder(sql=sql, dialect=DIALECT)
    assert len(h.queries_original) == 0
    assert len(h.collected_queries.unsupported) == 1


# Not supported by sqlglot: 'Falling back to Command'
def test__table_of_type(holder):
    sql = """
    CREATE TYPE person_type AS (
        first_name text,
        last_name text,
        age integer
    );

    CREATE TABLE employees OF person_type (
        PRIMARY KEY (first_name, last_name)
    );
    """
    h = holder(sql=sql, dialect=DIALECT)
    assert [TypeQuery] == h.query_types
    assert len(h.collected_queries.unsupported) == 1


def test__update_and_select_inherited(holder):
    sql = """
    CREATE TABLE fruit.parent (price NUMERIC);
    CREATE TABLE fruit.apple () INHERITS (fruit.parent);
    CREATE TABLE fruit.orange () INHERITS (fruit.parent);

    UPDATE fruit.apple
    SET price = s.price
    FROM (SELECT price FROM fruit.orange) AS s;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [["column[fruit.orange.price]", "column[fruit.apple.price]"]]
    assert len(h.nodes) == 2
    assert len(h.edges) == 1


def test__cte_only(holder):
    sql = """
    CREATE TABLE fruit.parent (name VARCHAR, kind VARCHAR);
    CREATE TABLE fruit.child () INHERITS (fruit.parent);
    CREATE TABLE fruit.output (name VARCHAR);

    WITH cte AS (
        SELECT name FROM ONLY fruit.parent
    )
    INSERT INTO fruit.output (name) SELECT name FROM cte;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [["column[fruit.parent.name]", "column[cte.name]", "column[fruit.output.name]"]]
    assert len(h.nodes) == 3
    assert len(h.edges) == 2


def test__update_only_inherited(holder):
    sql = """
    CREATE TABLE fruit.parent_table (price NUMERIC, quantity INT);
    CREATE TABLE fruit.child_table () INHERITS (fruit.parent_table);
    CREATE TABLE fruit.source_table (price NUMERIC);

    UPDATE ONLY fruit.parent_table
    SET price = s.price
    FROM (SELECT price FROM fruit.source_table) AS s;
    """
    h = holder(sql=sql, dialect=DIALECT)

    assert h.paths == [["column[fruit.source_table.price]", "column[fruit.parent_table.price]"]]
    assert len(h.nodes) == 2
    assert len(h.edges) == 1


def test__table_except_table_fails(holder):
    with pytest.raises(sqlglot.errors.ParseError) as e:
        sql = """
        INSERT INTO t1 TABLE t1 EXCEPT TABLE t2;
        """
        holder(sql=sql, dialect=DIALECT)
    assert e.value.args[0].startswith("Invalid expression / Unexpected token. Line 2, Col: 38.")


def test__select_inet_fails(holder):
    with pytest.raises(sqlglot.errors.ParseError) as e:
        sql = """
        INSERT INTO t1 (name) SELECT '192.168.1.1'::inet <<= '192.168.1.0/24'::inet
        """
        holder(sql=sql, dialect=DIALECT)
    assert e.value.args[0].startswith("Required keyword: 'expression' missing for")
